---
title: "sarimaTD_example"
author: "Graham Casey Gibson, Evan L. Ray, Nutcha Wattanachit"
date: "3/13/2020"
output: pdf_document
---

# An example of cdcForecast Utils for the sarimaTD model

First we load up sarimaTD and grab the cdc ILI data for Massachusetts.

```{r setup, include=T}
library(sarimaTD)
library(cdcForecastUtils)
library(lubridate)
library(dplyr)
```

```{r}
flu_data <- download_and_preprocess_state_flu_data()
ma_data <- flu_data[flu_data$region == "Massachusetts",]
plot(ma_data$unweighted_ili,type='l')
```



### Multiple States

```{r}
states <- unique(flu_data$region)[1:5]
states
```

Function to do all the steps to get the trajectories matrix for a single state:

```{r}
season_start <- "2020-EW10"

season_end <- "2020-EW35"
current_date_in_cdc_format <-paste0(tail(flu_data$year,1),"-EW", ifelse(nchar(tail(flu_data$week,1))==2,tail(flu_data$week,1),paste0("0",tail(flu_data$week,1))))

get_trajectories_one_state <- function(location, flu_data) {
  # subset to state data
  state_data <- flu_data[flu_data$region == location,]
  
  # fit sarima model
  sarimaFit <- sarimaTD::fit_sarima(tail(state_data$unweighted_ili,100),
    ts_frequency = 52)
  
  # times (could really be done once outside this function)
  
  forecast_horizon <- get_required_forecast_horizon(
    targets = c("wk ahead", "Peak height", "Peak week"),
    h_max = 6,
    season_end_ew = season_end,
    cdc_report_ew = current_date_in_cdc_format
  )
  
  # predictions
  preds <- simulate(
          object = sarimaFit,
          nsim = 1000,
          seed = 1,
          newdata = state_data$unweighted_ili,
          h = forecast_horizon
        )

  # prepend observed data
  time_from_start_of_season <- get_time_from_start_of_season(season_start,current_date_in_cdc_format)
  
  trajectory_matrix <- cbind(matrix(rep(tail(ma_data$unweighted_ili,time_from_start_of_season),1000),nrow=1000,byrow = T),preds)
  
  trajectory_matrix[trajectory_matrix < 0.0] <- 0.0
  trajectory_matrix[trajectory_matrix > 100] <- 100

  return(trajectory_matrix)
}
```

Call the function once for each state; assemble matrices in a tibble

```{r}
trajectories_by_state <- tibble(
  location = states
) %>%
  mutate(
    trajectories = purrr::map(
      states,
      get_trajectories_one_state,
      flu_data = flu_data)
  )
```

```{r}
trajectories_by_state
```

```{r}
submission_df <- multi_trajectories_to_binned_distributions(
  multi_trajectories = trajectories_by_state,
  targets = c("wk ahead", "Peak height", "Peak week"),
  h_max = 6,
  bins = c(seq(0, 25, by = .1), 100),
  season_start_ew = season_start,
  season_end_ew = season_end,
  cdc_report_ew = current_date_in_cdc_format)
```

```{r}
head(submission_df)
```

```{r}
submission_df %>%
  distinct(location, target) %>%
  as.data.frame()
head(submission_df)

point_forecasts <- generate_point_forecasts(submission_df,method="Median")
point_forecasts$forecast_week <- unique(submission_df$forecast_week)
point_forecasts
submission_df_w_point_fcasts <- rbind(submission_df,point_forecasts)

submission_df_w_point_fcasts$bin <- unlist(lapply(submission_df_w_point_fcasts$bin,function(x){
  if (!is.na(x)){
     if (nchar(x) <=2){
      return (paste0(x,".0"))
    }else{
      return (x)
    }
  }else{
    return (x)
  }
}))
verify_entry(submission_df_w_point_fcasts,challenge='state_ili')

generate_csv_from_submission_df(submission_df,"./")
sub_file<-read_entry("./2020-EW10.csv")
```

